//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionTbl
    {
        public CotizacionTbl()
        {
            this.DetalleCotizacionTbl = new HashSet<DetalleCotizacionTbl>();
        }
    
        public int ID_Cotizacion { get; set; }
        public int ID_Usuario { get; set; }
        public int Numero_Cotizacion { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Telefono_Cliente { get; set; }
        public string Correo_Cliente { get; set; }
        public System.DateTime Fecha_Cotizacion { get; set; }
        public System.TimeSpan Hora_Cotizacion { get; set; }
        public decimal Costo { get; set; }
    
        public virtual ICollection<DetalleCotizacionTbl> DetalleCotizacionTbl { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
