//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSalidaTbl
    {
        public int ID_DetalleSalida { get; set; }
        public int ID_Salida { get; set; }
        public int ID_Producto { get; set; }
        public int Cant_Salida_PROD { get; set; }
    
        public virtual ProductosTbl ProductosTbl { get; set; }
        public virtual SalidasTbl SalidasTbl { get; set; }
    }
}
