//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradasTbl
    {
        public EntradasTbl()
        {
            this.DetalleEntradaTbl = new HashSet<DetalleEntradaTbl>();
        }
    
        public int ID_Entrada { get; set; }
        public int ID_Proveedor { get; set; }
        public int ID_Usuario { get; set; }
        public int Numero_Factura { get; set; }
        public System.DateTime Fecha_Factura { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public decimal Monto_Bruto { get; set; }
        public decimal Monto_Descuento { get; set; }
        public decimal Monto_IVA { get; set; }
        public decimal Monto_Final { get; set; }
    
        public virtual ICollection<DetalleEntradaTbl> DetalleEntradaTbl { get; set; }
        public virtual ProveedoresTbl ProveedoresTbl { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
