//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgUsers
    {
        public int ID_ImgPerfil { get; set; }
        public int ID_Usuario { get; set; }
        public string urlImagenPerfil { get; set; }
        public string descripImg { get; set; }
    }
}
