//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MotoRepuestosMakoEntities : DbContext
    {
        public MotoRepuestosMakoEntities()
            : base("name=MotoRepuestosMakoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AjustesTbl> AjustesTbl { get; set; }
        public DbSet<CategoriasTbl> CategoriasTbl { get; set; }
        public DbSet<CitasTbl> CitasTbl { get; set; }
        public DbSet<CotizacionTbl> CotizacionTbl { get; set; }
        public DbSet<DetalleCotizacionTbl> DetalleCotizacionTbl { get; set; }
        public DbSet<DetalleEntradaTbl> DetalleEntradaTbl { get; set; }
        public DbSet<DetalleSalidaTbl> DetalleSalidaTbl { get; set; }
        public DbSet<EntradasTbl> EntradasTbl { get; set; }
        public DbSet<MarcaTbl> MarcaTbl { get; set; }
        public DbSet<ProveedoresTbl> ProveedoresTbl { get; set; }
        public DbSet<SalidasTbl> SalidasTbl { get; set; }
        public DbSet<ServiciosTbl> ServiciosTbl { get; set; }
        public DbSet<Tipo_ServicioTbl> Tipo_ServicioTbl { get; set; }
        public DbSet<TipoUsuario> TipoUsuario { get; set; }
        public DbSet<Desglose_SalidaView> Desglose_SalidaView { get; set; }
        public DbSet<CotizacionDesgloseView> CotizacionDesgloseView { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<ImagenesTbl> ImagenesTbl { get; set; }
        public DbSet<ProductosTbl> ProductosTbl { get; set; }
        public DbSet<Entradas_DesgloseView> Entradas_DesgloseView { get; set; }
    
        public virtual int sp_Elimina_Ajuste(Nullable<int> idAjuste)
        {
            var idAjusteParameter = idAjuste.HasValue ?
                new ObjectParameter("idAjuste", idAjuste) :
                new ObjectParameter("idAjuste", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Ajuste", idAjusteParameter);
        }
    
        public virtual int sp_Elimina_Categorias(Nullable<int> idCategoria)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Categorias", idCategoriaParameter);
        }
    
        public virtual int sp_Elimina_Citas(Nullable<int> idCita)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("idCita", idCita) :
                new ObjectParameter("idCita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Citas", idCitaParameter);
        }
    
        public virtual int sp_Elimina_Cotizacion(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("idCotizacion", idCotizacion) :
                new ObjectParameter("idCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Cotizacion", idCotizacionParameter);
        }
    
        public virtual int sp_Elimina_DetalleCoti(Nullable<int> idDetalleCoti)
        {
            var idDetalleCotiParameter = idDetalleCoti.HasValue ?
                new ObjectParameter("idDetalleCoti", idDetalleCoti) :
                new ObjectParameter("idDetalleCoti", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_DetalleCoti", idDetalleCotiParameter);
        }
    
        public virtual int sp_Elimina_DetalleEntrada(Nullable<int> idDetalleEnt)
        {
            var idDetalleEntParameter = idDetalleEnt.HasValue ?
                new ObjectParameter("idDetalleEnt", idDetalleEnt) :
                new ObjectParameter("idDetalleEnt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_DetalleEntrada", idDetalleEntParameter);
        }
    
        public virtual int sp_Elimina_DetalleSalida(Nullable<int> idDetalleSal)
        {
            var idDetalleSalParameter = idDetalleSal.HasValue ?
                new ObjectParameter("idDetalleSal", idDetalleSal) :
                new ObjectParameter("idDetalleSal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_DetalleSalida", idDetalleSalParameter);
        }
    
        public virtual int sp_Elimina_Entrada(Nullable<int> idEntrada)
        {
            var idEntradaParameter = idEntrada.HasValue ?
                new ObjectParameter("idEntrada", idEntrada) :
                new ObjectParameter("idEntrada", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Entrada", idEntradaParameter);
        }
    
        public virtual int sp_Elimina_Marca(Nullable<int> idMarca)
        {
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("idMarca", idMarca) :
                new ObjectParameter("idMarca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Marca", idMarcaParameter);
        }
    
        public virtual int sp_Elimina_Proveedor(Nullable<int> idProveedor)
        {
            var idProveedorParameter = idProveedor.HasValue ?
                new ObjectParameter("idProveedor", idProveedor) :
                new ObjectParameter("idProveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Proveedor", idProveedorParameter);
        }
    
        public virtual int sp_Elimina_Salida(Nullable<int> idsalida)
        {
            var idsalidaParameter = idsalida.HasValue ?
                new ObjectParameter("idsalida", idsalida) :
                new ObjectParameter("idsalida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Salida", idsalidaParameter);
        }
    
        public virtual int sp_Elimina_SERV_ID(Nullable<int> idSERV)
        {
            var idSERVParameter = idSERV.HasValue ?
                new ObjectParameter("idSERV", idSERV) :
                new ObjectParameter("idSERV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_SERV_ID", idSERVParameter);
        }
    
        public virtual int sp_Elimina_TipoSERVID(Nullable<int> idTipoSERV)
        {
            var idTipoSERVParameter = idTipoSERV.HasValue ?
                new ObjectParameter("idTipoSERV", idTipoSERV) :
                new ObjectParameter("idTipoSERV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_TipoSERVID", idTipoSERVParameter);
        }
    
        public virtual int sp_Elimina_TipoUsuario(Nullable<int> idTipousuario)
        {
            var idTipousuarioParameter = idTipousuario.HasValue ?
                new ObjectParameter("idTipousuario", idTipousuario) :
                new ObjectParameter("idTipousuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_TipoUsuario", idTipousuarioParameter);
        }
    
        public virtual int sp_Elimina_Usuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Usuario", idUsuarioParameter);
        }
    
        public virtual int sp_Inserta_Ajuste(Nullable<int> idProd, Nullable<int> idUsuario, string tipoAjuste, Nullable<int> cantAjuste, Nullable<System.DateTime> fechaAjuste, string descripAjuste)
        {
            var idProdParameter = idProd.HasValue ?
                new ObjectParameter("idProd", idProd) :
                new ObjectParameter("idProd", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var tipoAjusteParameter = tipoAjuste != null ?
                new ObjectParameter("tipoAjuste", tipoAjuste) :
                new ObjectParameter("tipoAjuste", typeof(string));
    
            var cantAjusteParameter = cantAjuste.HasValue ?
                new ObjectParameter("cantAjuste", cantAjuste) :
                new ObjectParameter("cantAjuste", typeof(int));
    
            var fechaAjusteParameter = fechaAjuste.HasValue ?
                new ObjectParameter("fechaAjuste", fechaAjuste) :
                new ObjectParameter("fechaAjuste", typeof(System.DateTime));
    
            var descripAjusteParameter = descripAjuste != null ?
                new ObjectParameter("descripAjuste", descripAjuste) :
                new ObjectParameter("descripAjuste", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Ajuste", idProdParameter, idUsuarioParameter, tipoAjusteParameter, cantAjusteParameter, fechaAjusteParameter, descripAjusteParameter);
        }
    
        public virtual int sp_Inserta_Categorias(string nombreCategoria, string descripCategoria)
        {
            var nombreCategoriaParameter = nombreCategoria != null ?
                new ObjectParameter("nombreCategoria", nombreCategoria) :
                new ObjectParameter("nombreCategoria", typeof(string));
    
            var descripCategoriaParameter = descripCategoria != null ?
                new ObjectParameter("descripCategoria", descripCategoria) :
                new ObjectParameter("descripCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Categorias", nombreCategoriaParameter, descripCategoriaParameter);
        }
    
        public virtual int sp_Inserta_Citas(Nullable<int> idUsuario, Nullable<int> idMarca, string nombreCliente, string numeroCliente, string placaMoto, Nullable<System.DateTime> fechaCita, Nullable<System.TimeSpan> horaCita, Nullable<System.DateTime> fechaIngreso)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("idMarca", idMarca) :
                new ObjectParameter("idMarca", typeof(int));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("nombreCliente", nombreCliente) :
                new ObjectParameter("nombreCliente", typeof(string));
    
            var numeroClienteParameter = numeroCliente != null ?
                new ObjectParameter("numeroCliente", numeroCliente) :
                new ObjectParameter("numeroCliente", typeof(string));
    
            var placaMotoParameter = placaMoto != null ?
                new ObjectParameter("placaMoto", placaMoto) :
                new ObjectParameter("placaMoto", typeof(string));
    
            var fechaCitaParameter = fechaCita.HasValue ?
                new ObjectParameter("fechaCita", fechaCita) :
                new ObjectParameter("fechaCita", typeof(System.DateTime));
    
            var horaCitaParameter = horaCita.HasValue ?
                new ObjectParameter("horaCita", horaCita) :
                new ObjectParameter("horaCita", typeof(System.TimeSpan));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("fechaIngreso", fechaIngreso) :
                new ObjectParameter("fechaIngreso", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Citas", idUsuarioParameter, idMarcaParameter, nombreClienteParameter, numeroClienteParameter, placaMotoParameter, fechaCitaParameter, horaCitaParameter, fechaIngresoParameter);
        }
    
        public virtual int sp_Inserta_Cotizacion(Nullable<int> idUsuario, Nullable<int> numCotizacion, string nombreCliente, string telefCliente, string correoCliente, Nullable<System.DateTime> fechaCotizacion, Nullable<System.TimeSpan> horaCotizacion, Nullable<decimal> costo)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var numCotizacionParameter = numCotizacion.HasValue ?
                new ObjectParameter("numCotizacion", numCotizacion) :
                new ObjectParameter("numCotizacion", typeof(int));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("nombreCliente", nombreCliente) :
                new ObjectParameter("nombreCliente", typeof(string));
    
            var telefClienteParameter = telefCliente != null ?
                new ObjectParameter("telefCliente", telefCliente) :
                new ObjectParameter("telefCliente", typeof(string));
    
            var correoClienteParameter = correoCliente != null ?
                new ObjectParameter("correoCliente", correoCliente) :
                new ObjectParameter("correoCliente", typeof(string));
    
            var fechaCotizacionParameter = fechaCotizacion.HasValue ?
                new ObjectParameter("fechaCotizacion", fechaCotizacion) :
                new ObjectParameter("fechaCotizacion", typeof(System.DateTime));
    
            var horaCotizacionParameter = horaCotizacion.HasValue ?
                new ObjectParameter("horaCotizacion", horaCotizacion) :
                new ObjectParameter("horaCotizacion", typeof(System.TimeSpan));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("costo", costo) :
                new ObjectParameter("costo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Cotizacion", idUsuarioParameter, numCotizacionParameter, nombreClienteParameter, telefClienteParameter, correoClienteParameter, fechaCotizacionParameter, horaCotizacionParameter, costoParameter);
        }
    
        public virtual int sp_Inserta_Detalle_Entrada(Nullable<int> idEntrada, Nullable<int> idProducto, Nullable<int> cantAdquirida, Nullable<decimal> precioXcant)
        {
            var idEntradaParameter = idEntrada.HasValue ?
                new ObjectParameter("idEntrada", idEntrada) :
                new ObjectParameter("idEntrada", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var cantAdquiridaParameter = cantAdquirida.HasValue ?
                new ObjectParameter("cantAdquirida", cantAdquirida) :
                new ObjectParameter("cantAdquirida", typeof(int));
    
            var precioXcantParameter = precioXcant.HasValue ?
                new ObjectParameter("precioXcant", precioXcant) :
                new ObjectParameter("precioXcant", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Detalle_Entrada", idEntradaParameter, idProductoParameter, cantAdquiridaParameter, precioXcantParameter);
        }
    
        public virtual int sp_Inserta_Detalle_Salida(Nullable<int> idSalida, Nullable<int> idProducto, Nullable<int> cantSalida)
        {
            var idSalidaParameter = idSalida.HasValue ?
                new ObjectParameter("idSalida", idSalida) :
                new ObjectParameter("idSalida", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var cantSalidaParameter = cantSalida.HasValue ?
                new ObjectParameter("cantSalida", cantSalida) :
                new ObjectParameter("cantSalida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Detalle_Salida", idSalidaParameter, idProductoParameter, cantSalidaParameter);
        }
    
        public virtual int sp_Inserta_DetalleCoti(Nullable<int> idCotizacion, Nullable<int> idProducto, Nullable<int> idServicio, Nullable<int> cantAquirida, Nullable<decimal> precioXcant)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("idCotizacion", idCotizacion) :
                new ObjectParameter("idCotizacion", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("idServicio", idServicio) :
                new ObjectParameter("idServicio", typeof(int));
    
            var cantAquiridaParameter = cantAquirida.HasValue ?
                new ObjectParameter("cantAquirida", cantAquirida) :
                new ObjectParameter("cantAquirida", typeof(int));
    
            var precioXcantParameter = precioXcant.HasValue ?
                new ObjectParameter("precioXcant", precioXcant) :
                new ObjectParameter("precioXcant", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_DetalleCoti", idCotizacionParameter, idProductoParameter, idServicioParameter, cantAquiridaParameter, precioXcantParameter);
        }
    
        public virtual int sp_Inserta_Entrada(Nullable<int> idProv, Nullable<int> idUsuario, Nullable<int> numFactura, Nullable<System.DateTime> fechaFactura, Nullable<System.DateTime> fechaRegistro, Nullable<decimal> montoBruto, Nullable<decimal> montoDescuento, Nullable<decimal> montoIVA, Nullable<decimal> montoFinal)
        {
            var idProvParameter = idProv.HasValue ?
                new ObjectParameter("idProv", idProv) :
                new ObjectParameter("idProv", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var numFacturaParameter = numFactura.HasValue ?
                new ObjectParameter("numFactura", numFactura) :
                new ObjectParameter("numFactura", typeof(int));
    
            var fechaFacturaParameter = fechaFactura.HasValue ?
                new ObjectParameter("fechaFactura", fechaFactura) :
                new ObjectParameter("fechaFactura", typeof(System.DateTime));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("fechaRegistro", fechaRegistro) :
                new ObjectParameter("fechaRegistro", typeof(System.DateTime));
    
            var montoBrutoParameter = montoBruto.HasValue ?
                new ObjectParameter("montoBruto", montoBruto) :
                new ObjectParameter("montoBruto", typeof(decimal));
    
            var montoDescuentoParameter = montoDescuento.HasValue ?
                new ObjectParameter("montoDescuento", montoDescuento) :
                new ObjectParameter("montoDescuento", typeof(decimal));
    
            var montoIVAParameter = montoIVA.HasValue ?
                new ObjectParameter("montoIVA", montoIVA) :
                new ObjectParameter("montoIVA", typeof(decimal));
    
            var montoFinalParameter = montoFinal.HasValue ?
                new ObjectParameter("montoFinal", montoFinal) :
                new ObjectParameter("montoFinal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Entrada", idProvParameter, idUsuarioParameter, numFacturaParameter, fechaFacturaParameter, fechaRegistroParameter, montoBrutoParameter, montoDescuentoParameter, montoIVAParameter, montoFinalParameter);
        }
    
        public virtual int sp_Inserta_Marcas(string nombreMarca, string descripcionMarca)
        {
            var nombreMarcaParameter = nombreMarca != null ?
                new ObjectParameter("nombreMarca", nombreMarca) :
                new ObjectParameter("nombreMarca", typeof(string));
    
            var descripcionMarcaParameter = descripcionMarca != null ?
                new ObjectParameter("descripcionMarca", descripcionMarca) :
                new ObjectParameter("descripcionMarca", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Marcas", nombreMarcaParameter, descripcionMarcaParameter);
        }
    
        public virtual int sp_Inserta_Proveedor(string nombreProv, string direccionProv, string correoProv, string telefonoProv, Nullable<bool> estadoProv)
        {
            var nombreProvParameter = nombreProv != null ?
                new ObjectParameter("nombreProv", nombreProv) :
                new ObjectParameter("nombreProv", typeof(string));
    
            var direccionProvParameter = direccionProv != null ?
                new ObjectParameter("direccionProv", direccionProv) :
                new ObjectParameter("direccionProv", typeof(string));
    
            var correoProvParameter = correoProv != null ?
                new ObjectParameter("correoProv", correoProv) :
                new ObjectParameter("correoProv", typeof(string));
    
            var telefonoProvParameter = telefonoProv != null ?
                new ObjectParameter("telefonoProv", telefonoProv) :
                new ObjectParameter("telefonoProv", typeof(string));
    
            var estadoProvParameter = estadoProv.HasValue ?
                new ObjectParameter("estadoProv", estadoProv) :
                new ObjectParameter("estadoProv", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Proveedor", nombreProvParameter, direccionProvParameter, correoProvParameter, telefonoProvParameter, estadoProvParameter);
        }
    
        public virtual int sp_Inserta_Salida(Nullable<int> idUsuario, Nullable<System.DateTime> fechaRegistro, Nullable<System.TimeSpan> horaOrden)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("fechaRegistro", fechaRegistro) :
                new ObjectParameter("fechaRegistro", typeof(System.DateTime));
    
            var horaOrdenParameter = horaOrden.HasValue ?
                new ObjectParameter("horaOrden", horaOrden) :
                new ObjectParameter("horaOrden", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Salida", idUsuarioParameter, fechaRegistroParameter, horaOrdenParameter);
        }
    
        public virtual int sp_Inserta_Servicio(Nullable<int> idTipoSERV, string nombreSERV, Nullable<decimal> precioSERV)
        {
            var idTipoSERVParameter = idTipoSERV.HasValue ?
                new ObjectParameter("idTipoSERV", idTipoSERV) :
                new ObjectParameter("idTipoSERV", typeof(int));
    
            var nombreSERVParameter = nombreSERV != null ?
                new ObjectParameter("nombreSERV", nombreSERV) :
                new ObjectParameter("nombreSERV", typeof(string));
    
            var precioSERVParameter = precioSERV.HasValue ?
                new ObjectParameter("precioSERV", precioSERV) :
                new ObjectParameter("precioSERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Servicio", idTipoSERVParameter, nombreSERVParameter, precioSERVParameter);
        }
    
        public virtual int sp_Inserta_TipoSERV(string nombreTIPOSERV, string descripTipoSERV)
        {
            var nombreTIPOSERVParameter = nombreTIPOSERV != null ?
                new ObjectParameter("nombreTIPOSERV", nombreTIPOSERV) :
                new ObjectParameter("nombreTIPOSERV", typeof(string));
    
            var descripTipoSERVParameter = descripTipoSERV != null ?
                new ObjectParameter("descripTipoSERV", descripTipoSERV) :
                new ObjectParameter("descripTipoSERV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_TipoSERV", nombreTIPOSERVParameter, descripTipoSERVParameter);
        }
    
        public virtual int sp_Inserta_TipoUsuario(string nombreTipoUsuario)
        {
            var nombreTipoUsuarioParameter = nombreTipoUsuario != null ?
                new ObjectParameter("nombreTipoUsuario", nombreTipoUsuario) :
                new ObjectParameter("nombreTipoUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_TipoUsuario", nombreTipoUsuarioParameter);
        }
    
        public virtual int sp_Modifica_Ajuste(Nullable<int> idAjuste, Nullable<int> idProd, Nullable<int> idUsuario, string tipoAjuste, Nullable<int> cantAjuste, Nullable<System.DateTime> fechaAjuste, string descripAjuste)
        {
            var idAjusteParameter = idAjuste.HasValue ?
                new ObjectParameter("idAjuste", idAjuste) :
                new ObjectParameter("idAjuste", typeof(int));
    
            var idProdParameter = idProd.HasValue ?
                new ObjectParameter("idProd", idProd) :
                new ObjectParameter("idProd", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var tipoAjusteParameter = tipoAjuste != null ?
                new ObjectParameter("tipoAjuste", tipoAjuste) :
                new ObjectParameter("tipoAjuste", typeof(string));
    
            var cantAjusteParameter = cantAjuste.HasValue ?
                new ObjectParameter("cantAjuste", cantAjuste) :
                new ObjectParameter("cantAjuste", typeof(int));
    
            var fechaAjusteParameter = fechaAjuste.HasValue ?
                new ObjectParameter("fechaAjuste", fechaAjuste) :
                new ObjectParameter("fechaAjuste", typeof(System.DateTime));
    
            var descripAjusteParameter = descripAjuste != null ?
                new ObjectParameter("descripAjuste", descripAjuste) :
                new ObjectParameter("descripAjuste", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Ajuste", idAjusteParameter, idProdParameter, idUsuarioParameter, tipoAjusteParameter, cantAjusteParameter, fechaAjusteParameter, descripAjusteParameter);
        }
    
        public virtual int sp_Modifica_Categorias(Nullable<int> idCategoria, string nombreCategoria, string descripCategoria)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            var nombreCategoriaParameter = nombreCategoria != null ?
                new ObjectParameter("nombreCategoria", nombreCategoria) :
                new ObjectParameter("nombreCategoria", typeof(string));
    
            var descripCategoriaParameter = descripCategoria != null ?
                new ObjectParameter("descripCategoria", descripCategoria) :
                new ObjectParameter("descripCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Categorias", idCategoriaParameter, nombreCategoriaParameter, descripCategoriaParameter);
        }
    
        public virtual int sp_Modifica_Citas(Nullable<int> idCita, Nullable<int> idUsuario, Nullable<int> idMarca, string nombreCliente, string numeroCliente, string placaMoto, Nullable<System.DateTime> fechaCita, Nullable<System.TimeSpan> horaCita, Nullable<System.DateTime> fechaIngreso)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("idCita", idCita) :
                new ObjectParameter("idCita", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("idMarca", idMarca) :
                new ObjectParameter("idMarca", typeof(int));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("nombreCliente", nombreCliente) :
                new ObjectParameter("nombreCliente", typeof(string));
    
            var numeroClienteParameter = numeroCliente != null ?
                new ObjectParameter("numeroCliente", numeroCliente) :
                new ObjectParameter("numeroCliente", typeof(string));
    
            var placaMotoParameter = placaMoto != null ?
                new ObjectParameter("placaMoto", placaMoto) :
                new ObjectParameter("placaMoto", typeof(string));
    
            var fechaCitaParameter = fechaCita.HasValue ?
                new ObjectParameter("fechaCita", fechaCita) :
                new ObjectParameter("fechaCita", typeof(System.DateTime));
    
            var horaCitaParameter = horaCita.HasValue ?
                new ObjectParameter("horaCita", horaCita) :
                new ObjectParameter("horaCita", typeof(System.TimeSpan));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("fechaIngreso", fechaIngreso) :
                new ObjectParameter("fechaIngreso", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Citas", idCitaParameter, idUsuarioParameter, idMarcaParameter, nombreClienteParameter, numeroClienteParameter, placaMotoParameter, fechaCitaParameter, horaCitaParameter, fechaIngresoParameter);
        }
    
        public virtual int sp_Modifica_Cotizacion(Nullable<int> idCotizacon, Nullable<int> idUsuario, Nullable<int> numCotizacion, string nombreCliente, string telefCliente, string correoCliente, Nullable<System.DateTime> fechaCotizacion, Nullable<System.TimeSpan> horaCotizacion, Nullable<decimal> costo)
        {
            var idCotizaconParameter = idCotizacon.HasValue ?
                new ObjectParameter("idCotizacon", idCotizacon) :
                new ObjectParameter("idCotizacon", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var numCotizacionParameter = numCotizacion.HasValue ?
                new ObjectParameter("numCotizacion", numCotizacion) :
                new ObjectParameter("numCotizacion", typeof(int));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("nombreCliente", nombreCliente) :
                new ObjectParameter("nombreCliente", typeof(string));
    
            var telefClienteParameter = telefCliente != null ?
                new ObjectParameter("telefCliente", telefCliente) :
                new ObjectParameter("telefCliente", typeof(string));
    
            var correoClienteParameter = correoCliente != null ?
                new ObjectParameter("correoCliente", correoCliente) :
                new ObjectParameter("correoCliente", typeof(string));
    
            var fechaCotizacionParameter = fechaCotizacion.HasValue ?
                new ObjectParameter("fechaCotizacion", fechaCotizacion) :
                new ObjectParameter("fechaCotizacion", typeof(System.DateTime));
    
            var horaCotizacionParameter = horaCotizacion.HasValue ?
                new ObjectParameter("horaCotizacion", horaCotizacion) :
                new ObjectParameter("horaCotizacion", typeof(System.TimeSpan));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("costo", costo) :
                new ObjectParameter("costo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Cotizacion", idCotizaconParameter, idUsuarioParameter, numCotizacionParameter, nombreClienteParameter, telefClienteParameter, correoClienteParameter, fechaCotizacionParameter, horaCotizacionParameter, costoParameter);
        }
    
        public virtual int sp_Modifica_Detalle_Entrada(Nullable<int> idDetalleEntr, Nullable<int> idEntrada, Nullable<int> idProducto, Nullable<int> cantAdquirida, Nullable<decimal> precioXcant)
        {
            var idDetalleEntrParameter = idDetalleEntr.HasValue ?
                new ObjectParameter("idDetalleEntr", idDetalleEntr) :
                new ObjectParameter("idDetalleEntr", typeof(int));
    
            var idEntradaParameter = idEntrada.HasValue ?
                new ObjectParameter("idEntrada", idEntrada) :
                new ObjectParameter("idEntrada", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var cantAdquiridaParameter = cantAdquirida.HasValue ?
                new ObjectParameter("cantAdquirida", cantAdquirida) :
                new ObjectParameter("cantAdquirida", typeof(int));
    
            var precioXcantParameter = precioXcant.HasValue ?
                new ObjectParameter("precioXcant", precioXcant) :
                new ObjectParameter("precioXcant", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Detalle_Entrada", idDetalleEntrParameter, idEntradaParameter, idProductoParameter, cantAdquiridaParameter, precioXcantParameter);
        }
    
        public virtual int sp_Modifica_Detalle_Salida(Nullable<int> idDetalleSal, Nullable<int> idSalida, Nullable<int> idProducto, Nullable<int> cantSalida)
        {
            var idDetalleSalParameter = idDetalleSal.HasValue ?
                new ObjectParameter("idDetalleSal", idDetalleSal) :
                new ObjectParameter("idDetalleSal", typeof(int));
    
            var idSalidaParameter = idSalida.HasValue ?
                new ObjectParameter("idSalida", idSalida) :
                new ObjectParameter("idSalida", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var cantSalidaParameter = cantSalida.HasValue ?
                new ObjectParameter("cantSalida", cantSalida) :
                new ObjectParameter("cantSalida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Detalle_Salida", idDetalleSalParameter, idSalidaParameter, idProductoParameter, cantSalidaParameter);
        }
    
        public virtual int sp_Modifica_DetalleCoti(Nullable<int> idDetalleCoti, Nullable<int> idCotizacion, Nullable<int> idProducto, Nullable<int> idServicio, Nullable<int> cantAquirida, Nullable<decimal> precioXcant)
        {
            var idDetalleCotiParameter = idDetalleCoti.HasValue ?
                new ObjectParameter("idDetalleCoti", idDetalleCoti) :
                new ObjectParameter("idDetalleCoti", typeof(int));
    
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("idCotizacion", idCotizacion) :
                new ObjectParameter("idCotizacion", typeof(int));
    
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            var idServicioParameter = idServicio.HasValue ?
                new ObjectParameter("idServicio", idServicio) :
                new ObjectParameter("idServicio", typeof(int));
    
            var cantAquiridaParameter = cantAquirida.HasValue ?
                new ObjectParameter("cantAquirida", cantAquirida) :
                new ObjectParameter("cantAquirida", typeof(int));
    
            var precioXcantParameter = precioXcant.HasValue ?
                new ObjectParameter("precioXcant", precioXcant) :
                new ObjectParameter("precioXcant", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_DetalleCoti", idDetalleCotiParameter, idCotizacionParameter, idProductoParameter, idServicioParameter, cantAquiridaParameter, precioXcantParameter);
        }
    
        public virtual int sp_Modifica_Entrada(Nullable<int> idEntrada, Nullable<int> idProv, Nullable<int> idUsuario, Nullable<int> numFactura, Nullable<System.DateTime> fechaFactura, Nullable<System.DateTime> fechaRegistro, Nullable<decimal> montoBruto, Nullable<decimal> montoDescuento, Nullable<decimal> montoIVA, Nullable<decimal> montoFinal)
        {
            var idEntradaParameter = idEntrada.HasValue ?
                new ObjectParameter("idEntrada", idEntrada) :
                new ObjectParameter("idEntrada", typeof(int));
    
            var idProvParameter = idProv.HasValue ?
                new ObjectParameter("idProv", idProv) :
                new ObjectParameter("idProv", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var numFacturaParameter = numFactura.HasValue ?
                new ObjectParameter("numFactura", numFactura) :
                new ObjectParameter("numFactura", typeof(int));
    
            var fechaFacturaParameter = fechaFactura.HasValue ?
                new ObjectParameter("fechaFactura", fechaFactura) :
                new ObjectParameter("fechaFactura", typeof(System.DateTime));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("fechaRegistro", fechaRegistro) :
                new ObjectParameter("fechaRegistro", typeof(System.DateTime));
    
            var montoBrutoParameter = montoBruto.HasValue ?
                new ObjectParameter("montoBruto", montoBruto) :
                new ObjectParameter("montoBruto", typeof(decimal));
    
            var montoDescuentoParameter = montoDescuento.HasValue ?
                new ObjectParameter("montoDescuento", montoDescuento) :
                new ObjectParameter("montoDescuento", typeof(decimal));
    
            var montoIVAParameter = montoIVA.HasValue ?
                new ObjectParameter("montoIVA", montoIVA) :
                new ObjectParameter("montoIVA", typeof(decimal));
    
            var montoFinalParameter = montoFinal.HasValue ?
                new ObjectParameter("montoFinal", montoFinal) :
                new ObjectParameter("montoFinal", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Entrada", idEntradaParameter, idProvParameter, idUsuarioParameter, numFacturaParameter, fechaFacturaParameter, fechaRegistroParameter, montoBrutoParameter, montoDescuentoParameter, montoIVAParameter, montoFinalParameter);
        }
    
        public virtual int sp_Modifica_Marcas(Nullable<int> idMarca, string nombreMarca, string descripcionMarca)
        {
            var idMarcaParameter = idMarca.HasValue ?
                new ObjectParameter("idMarca", idMarca) :
                new ObjectParameter("idMarca", typeof(int));
    
            var nombreMarcaParameter = nombreMarca != null ?
                new ObjectParameter("nombreMarca", nombreMarca) :
                new ObjectParameter("nombreMarca", typeof(string));
    
            var descripcionMarcaParameter = descripcionMarca != null ?
                new ObjectParameter("descripcionMarca", descripcionMarca) :
                new ObjectParameter("descripcionMarca", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Marcas", idMarcaParameter, nombreMarcaParameter, descripcionMarcaParameter);
        }
    
        public virtual int sp_Modifica_ProveedorID(Nullable<int> idprov, string nombreProv, string direccionProv, string correoProv, string telefonoProv, Nullable<bool> estadoProv)
        {
            var idprovParameter = idprov.HasValue ?
                new ObjectParameter("idprov", idprov) :
                new ObjectParameter("idprov", typeof(int));
    
            var nombreProvParameter = nombreProv != null ?
                new ObjectParameter("nombreProv", nombreProv) :
                new ObjectParameter("nombreProv", typeof(string));
    
            var direccionProvParameter = direccionProv != null ?
                new ObjectParameter("direccionProv", direccionProv) :
                new ObjectParameter("direccionProv", typeof(string));
    
            var correoProvParameter = correoProv != null ?
                new ObjectParameter("correoProv", correoProv) :
                new ObjectParameter("correoProv", typeof(string));
    
            var telefonoProvParameter = telefonoProv != null ?
                new ObjectParameter("telefonoProv", telefonoProv) :
                new ObjectParameter("telefonoProv", typeof(string));
    
            var estadoProvParameter = estadoProv.HasValue ?
                new ObjectParameter("estadoProv", estadoProv) :
                new ObjectParameter("estadoProv", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_ProveedorID", idprovParameter, nombreProvParameter, direccionProvParameter, correoProvParameter, telefonoProvParameter, estadoProvParameter);
        }
    
        public virtual int sp_Modifica_Salida(Nullable<int> idSalida, Nullable<int> idUsuario, Nullable<System.DateTime> fechaRegistro, Nullable<System.TimeSpan> horaOrden)
        {
            var idSalidaParameter = idSalida.HasValue ?
                new ObjectParameter("idSalida", idSalida) :
                new ObjectParameter("idSalida", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("fechaRegistro", fechaRegistro) :
                new ObjectParameter("fechaRegistro", typeof(System.DateTime));
    
            var horaOrdenParameter = horaOrden.HasValue ?
                new ObjectParameter("horaOrden", horaOrden) :
                new ObjectParameter("horaOrden", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Salida", idSalidaParameter, idUsuarioParameter, fechaRegistroParameter, horaOrdenParameter);
        }
    
        public virtual int sp_Modifica_Servicio(Nullable<int> idservicio, Nullable<int> idTipoSERV, string nombreSERV, Nullable<decimal> precioSERV)
        {
            var idservicioParameter = idservicio.HasValue ?
                new ObjectParameter("idservicio", idservicio) :
                new ObjectParameter("idservicio", typeof(int));
    
            var idTipoSERVParameter = idTipoSERV.HasValue ?
                new ObjectParameter("idTipoSERV", idTipoSERV) :
                new ObjectParameter("idTipoSERV", typeof(int));
    
            var nombreSERVParameter = nombreSERV != null ?
                new ObjectParameter("nombreSERV", nombreSERV) :
                new ObjectParameter("nombreSERV", typeof(string));
    
            var precioSERVParameter = precioSERV.HasValue ?
                new ObjectParameter("precioSERV", precioSERV) :
                new ObjectParameter("precioSERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Servicio", idservicioParameter, idTipoSERVParameter, nombreSERVParameter, precioSERVParameter);
        }
    
        public virtual int sp_Modifica_TipoSERV(Nullable<int> idTipoSERV, string nombreTIPOSERV, string descripTipoSERV)
        {
            var idTipoSERVParameter = idTipoSERV.HasValue ?
                new ObjectParameter("idTipoSERV", idTipoSERV) :
                new ObjectParameter("idTipoSERV", typeof(int));
    
            var nombreTIPOSERVParameter = nombreTIPOSERV != null ?
                new ObjectParameter("nombreTIPOSERV", nombreTIPOSERV) :
                new ObjectParameter("nombreTIPOSERV", typeof(string));
    
            var descripTipoSERVParameter = descripTipoSERV != null ?
                new ObjectParameter("descripTipoSERV", descripTipoSERV) :
                new ObjectParameter("descripTipoSERV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_TipoSERV", idTipoSERVParameter, nombreTIPOSERVParameter, descripTipoSERVParameter);
        }
    
        public virtual int sp_Modifica_TipoUsuario(Nullable<int> idTipousuario, string nombreTipoUsuario)
        {
            var idTipousuarioParameter = idTipousuario.HasValue ?
                new ObjectParameter("idTipousuario", idTipousuario) :
                new ObjectParameter("idTipousuario", typeof(int));
    
            var nombreTipoUsuarioParameter = nombreTipoUsuario != null ?
                new ObjectParameter("nombreTipoUsuario", nombreTipoUsuario) :
                new ObjectParameter("nombreTipoUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_TipoUsuario", idTipousuarioParameter, nombreTipoUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_AjusteID_Result> sp_Retorna_AjusteID(Nullable<int> idAjuste)
        {
            var idAjusteParameter = idAjuste.HasValue ?
                new ObjectParameter("idAjuste", idAjuste) :
                new ObjectParameter("idAjuste", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_AjusteID_Result>("sp_Retorna_AjusteID", idAjusteParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Ajustes_Result> sp_Retorna_Ajustes(string tipoAjuste)
        {
            var tipoAjusteParameter = tipoAjuste != null ?
                new ObjectParameter("tipoAjuste", tipoAjuste) :
                new ObjectParameter("tipoAjuste", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Ajustes_Result>("sp_Retorna_Ajustes", tipoAjusteParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Categorias_Result> sp_Retorna_Categorias(string nombreCategoria, string descripCategoria)
        {
            var nombreCategoriaParameter = nombreCategoria != null ?
                new ObjectParameter("nombreCategoria", nombreCategoria) :
                new ObjectParameter("nombreCategoria", typeof(string));
    
            var descripCategoriaParameter = descripCategoria != null ?
                new ObjectParameter("descripCategoria", descripCategoria) :
                new ObjectParameter("descripCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Categorias_Result>("sp_Retorna_Categorias", nombreCategoriaParameter, descripCategoriaParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Categorias_ID_Result> sp_Retorna_Categorias_ID(Nullable<int> idCategoria)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Categorias_ID_Result>("sp_Retorna_Categorias_ID", idCategoriaParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Citas_Result> sp_Retorna_Citas(string nombreCliente, string placaMoto)
        {
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("nombreCliente", nombreCliente) :
                new ObjectParameter("nombreCliente", typeof(string));
    
            var placaMotoParameter = placaMoto != null ?
                new ObjectParameter("placaMoto", placaMoto) :
                new ObjectParameter("placaMoto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Citas_Result>("sp_Retorna_Citas", nombreClienteParameter, placaMotoParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_CitasID_Result> sp_Retorna_CitasID(Nullable<int> idCita)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("idCita", idCita) :
                new ObjectParameter("idCita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_CitasID_Result>("sp_Retorna_CitasID", idCitaParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Cotizacion_Result> sp_Retorna_Cotizacion(string nombreCliente, string correoCliente)
        {
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("nombreCliente", nombreCliente) :
                new ObjectParameter("nombreCliente", typeof(string));
    
            var correoClienteParameter = correoCliente != null ?
                new ObjectParameter("correoCliente", correoCliente) :
                new ObjectParameter("correoCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Cotizacion_Result>("sp_Retorna_Cotizacion", nombreClienteParameter, correoClienteParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_CotizacionID_Result> sp_Retorna_CotizacionID(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("idCotizacion", idCotizacion) :
                new ObjectParameter("idCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_CotizacionID_Result>("sp_Retorna_CotizacionID", idCotizacionParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Detalle_EntrID_Result> sp_Retorna_Detalle_EntrID(Nullable<int> idDetalleEntr)
        {
            var idDetalleEntrParameter = idDetalleEntr.HasValue ?
                new ObjectParameter("idDetalleEntr", idDetalleEntr) :
                new ObjectParameter("idDetalleEntr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Detalle_EntrID_Result>("sp_Retorna_Detalle_EntrID", idDetalleEntrParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Detalle_Salida_Result> sp_Retorna_Detalle_Salida(Nullable<int> idDetalleSal)
        {
            var idDetalleSalParameter = idDetalleSal.HasValue ?
                new ObjectParameter("idDetalleSal", idDetalleSal) :
                new ObjectParameter("idDetalleSal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Detalle_Salida_Result>("sp_Retorna_Detalle_Salida", idDetalleSalParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_DetalleCoti_Result> sp_Retorna_DetalleCoti(Nullable<int> idDetalleCoti)
        {
            var idDetalleCotiParameter = idDetalleCoti.HasValue ?
                new ObjectParameter("idDetalleCoti", idDetalleCoti) :
                new ObjectParameter("idDetalleCoti", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_DetalleCoti_Result>("sp_Retorna_DetalleCoti", idDetalleCotiParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_EntradaID_Result> sp_Retorna_EntradaID(Nullable<int> idEntrada)
        {
            var idEntradaParameter = idEntrada.HasValue ?
                new ObjectParameter("idEntrada", idEntrada) :
                new ObjectParameter("idEntrada", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_EntradaID_Result>("sp_Retorna_EntradaID", idEntradaParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Entradas_Result> sp_Retorna_Entradas(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Entradas_Result>("sp_Retorna_Entradas", idUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Marcas_Result> sp_Retorna_Marcas(string nombreMarca, string descripcion)
        {
            var nombreMarcaParameter = nombreMarca != null ?
                new ObjectParameter("nombreMarca", nombreMarca) :
                new ObjectParameter("nombreMarca", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Marcas_Result>("sp_Retorna_Marcas", nombreMarcaParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Marcas_ID_Result> sp_Retorna_Marcas_ID(Nullable<int> iD_Marca)
        {
            var iD_MarcaParameter = iD_Marca.HasValue ?
                new ObjectParameter("ID_Marca", iD_Marca) :
                new ObjectParameter("ID_Marca", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Marcas_ID_Result>("sp_Retorna_Marcas_ID", iD_MarcaParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Proveedores_Result> sp_Retorna_Proveedores(string nombreProv)
        {
            var nombreProvParameter = nombreProv != null ?
                new ObjectParameter("nombreProv", nombreProv) :
                new ObjectParameter("nombreProv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Proveedores_Result>("sp_Retorna_Proveedores", nombreProvParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_ProveedorID_Result> sp_Retorna_ProveedorID(Nullable<int> idprov)
        {
            var idprovParameter = idprov.HasValue ?
                new ObjectParameter("idprov", idprov) :
                new ObjectParameter("idprov", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_ProveedorID_Result>("sp_Retorna_ProveedorID", idprovParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_SalidaID_Result> sp_Retorna_SalidaID(Nullable<int> idSalida)
        {
            var idSalidaParameter = idSalida.HasValue ?
                new ObjectParameter("idSalida", idSalida) :
                new ObjectParameter("idSalida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_SalidaID_Result>("sp_Retorna_SalidaID", idSalidaParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Serv_ID_Result> sp_Retorna_Serv_ID(Nullable<int> idSERV)
        {
            var idSERVParameter = idSERV.HasValue ?
                new ObjectParameter("idSERV", idSERV) :
                new ObjectParameter("idSERV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Serv_ID_Result>("sp_Retorna_Serv_ID", idSERVParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Servicio_Result> sp_Retorna_Servicio(string nombreSERV)
        {
            var nombreSERVParameter = nombreSERV != null ?
                new ObjectParameter("nombreSERV", nombreSERV) :
                new ObjectParameter("nombreSERV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Servicio_Result>("sp_Retorna_Servicio", nombreSERVParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Tipo_SERV_ID_Result> sp_Retorna_Tipo_SERV_ID(Nullable<int> idTipoSERV)
        {
            var idTipoSERVParameter = idTipoSERV.HasValue ?
                new ObjectParameter("idTipoSERV", idTipoSERV) :
                new ObjectParameter("idTipoSERV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Tipo_SERV_ID_Result>("sp_Retorna_Tipo_SERV_ID", idTipoSERVParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Tipo_Servicio_Result> sp_Retorna_Tipo_Servicio(string nombreTipoSERV, string descripTipoSERV)
        {
            var nombreTipoSERVParameter = nombreTipoSERV != null ?
                new ObjectParameter("nombreTipoSERV", nombreTipoSERV) :
                new ObjectParameter("nombreTipoSERV", typeof(string));
    
            var descripTipoSERVParameter = descripTipoSERV != null ?
                new ObjectParameter("descripTipoSERV", descripTipoSERV) :
                new ObjectParameter("descripTipoSERV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Tipo_Servicio_Result>("sp_Retorna_Tipo_Servicio", nombreTipoSERVParameter, descripTipoSERVParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_TipoUsuario_Result> sp_Retorna_TipoUsuario(string nombreTipoUsu)
        {
            var nombreTipoUsuParameter = nombreTipoUsu != null ?
                new ObjectParameter("nombreTipoUsu", nombreTipoUsu) :
                new ObjectParameter("nombreTipoUsu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_TipoUsuario_Result>("sp_Retorna_TipoUsuario", nombreTipoUsuParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_TipoUsuario_ID_Result> sp_Retorna_TipoUsuario_ID(Nullable<int> idTipousuario)
        {
            var idTipousuarioParameter = idTipousuario.HasValue ?
                new ObjectParameter("idTipousuario", idTipousuario) :
                new ObjectParameter("idTipousuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_TipoUsuario_ID_Result>("sp_Retorna_TipoUsuario_ID", idTipousuarioParameter);
        }
    
        public virtual int sp_Elimina_Products(Nullable<int> idPROD)
        {
            var idPRODParameter = idPROD.HasValue ?
                new ObjectParameter("idPROD", idPROD) :
                new ObjectParameter("idPROD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Elimina_Products", idPRODParameter);
        }
    
        public virtual ObjectResult<sp_Verifica_Usuario_Result> sp_Verifica_Usuario(string nombreU, string claveU)
        {
            var nombreUParameter = nombreU != null ?
                new ObjectParameter("nombreU", nombreU) :
                new ObjectParameter("nombreU", typeof(string));
    
            var claveUParameter = claveU != null ?
                new ObjectParameter("claveU", claveU) :
                new ObjectParameter("claveU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Verifica_Usuario_Result>("sp_Verifica_Usuario", nombreUParameter, claveUParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Detalle_Entradas_Result> sp_Retorna_Detalle_Entradas(Nullable<int> idDetalleEntr)
        {
            var idDetalleEntrParameter = idDetalleEntr.HasValue ?
                new ObjectParameter("idDetalleEntr", idDetalleEntr) :
                new ObjectParameter("idDetalleEntr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Detalle_Entradas_Result>("sp_Retorna_Detalle_Entradas", idDetalleEntrParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Detalle_FacturaID_Result> sp_Retorna_Detalle_FacturaID(Nullable<int> idEntr)
        {
            var idEntrParameter = idEntr.HasValue ?
                new ObjectParameter("idEntr", idEntr) :
                new ObjectParameter("idEntr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Detalle_FacturaID_Result>("sp_Retorna_Detalle_FacturaID", idEntrParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_FacturaID_Result> sp_Retorna_FacturaID(Nullable<int> idEntr)
        {
            var idEntrParameter = idEntr.HasValue ?
                new ObjectParameter("idEntr", idEntr) :
                new ObjectParameter("idEntr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_FacturaID_Result>("sp_Retorna_FacturaID", idEntrParameter);
        }
    
        public virtual ObjectResult<sp_VerificaDatos_Usuario_Result> sp_VerificaDatos_Usuario(string nombreUsuario, string correoUsuario)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("nombreUsuario", nombreUsuario) :
                new ObjectParameter("nombreUsuario", typeof(string));
    
            var correoUsuarioParameter = correoUsuario != null ?
                new ObjectParameter("correoUsuario", correoUsuario) :
                new ObjectParameter("correoUsuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_VerificaDatos_Usuario_Result>("sp_VerificaDatos_Usuario", nombreUsuarioParameter, correoUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_DetalleFacturaSalida_Result> sp_Retorna_DetalleFacturaSalida(Nullable<int> idSalida)
        {
            var idSalidaParameter = idSalida.HasValue ?
                new ObjectParameter("idSalida", idSalida) :
                new ObjectParameter("idSalida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_DetalleFacturaSalida_Result>("sp_Retorna_DetalleFacturaSalida", idSalidaParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_DesgloseSalida_Result> sp_Retorna_DesgloseSalida(Nullable<int> idSal)
        {
            var idSalParameter = idSal.HasValue ?
                new ObjectParameter("idSal", idSal) :
                new ObjectParameter("idSal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_DesgloseSalida_Result>("sp_Retorna_DesgloseSalida", idSalParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_DesgloseCotizacion_Result> sp_Retorna_DesgloseCotizacion(Nullable<int> idCot)
        {
            var idCotParameter = idCot.HasValue ?
                new ObjectParameter("idCot", idCot) :
                new ObjectParameter("idCot", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_DesgloseCotizacion_Result>("sp_Retorna_DesgloseCotizacion", idCotParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_DetalleCotID_Result> sp_Retorna_DetalleCotID(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("idCotizacion", idCotizacion) :
                new ObjectParameter("idCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_DetalleCotID_Result>("sp_Retorna_DetalleCotID", idCotizacionParameter);
        }
    
        public virtual int sp_Inserta_Usuario(Nullable<int> idTipoUsuario, string nombreUsuario, string apellido1, string apellido2, string direccion, string correo, string telefono, string clave, string usuarioIngreso, string estadoU, Nullable<System.DateTime> fechaCreado, Nullable<System.DateTime> ultimaVez, string cedula)
        {
            var idTipoUsuarioParameter = idTipoUsuario.HasValue ?
                new ObjectParameter("idTipoUsuario", idTipoUsuario) :
                new ObjectParameter("idTipoUsuario", typeof(int));
    
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("nombreUsuario", nombreUsuario) :
                new ObjectParameter("nombreUsuario", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var usuarioIngresoParameter = usuarioIngreso != null ?
                new ObjectParameter("usuarioIngreso", usuarioIngreso) :
                new ObjectParameter("usuarioIngreso", typeof(string));
    
            var estadoUParameter = estadoU != null ?
                new ObjectParameter("estadoU", estadoU) :
                new ObjectParameter("estadoU", typeof(string));
    
            var fechaCreadoParameter = fechaCreado.HasValue ?
                new ObjectParameter("fechaCreado", fechaCreado) :
                new ObjectParameter("fechaCreado", typeof(System.DateTime));
    
            var ultimaVezParameter = ultimaVez.HasValue ?
                new ObjectParameter("ultimaVez", ultimaVez) :
                new ObjectParameter("ultimaVez", typeof(System.DateTime));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Usuario", idTipoUsuarioParameter, nombreUsuarioParameter, apellido1Parameter, apellido2Parameter, direccionParameter, correoParameter, telefonoParameter, claveParameter, usuarioIngresoParameter, estadoUParameter, fechaCreadoParameter, ultimaVezParameter, cedulaParameter);
        }
    
        public virtual int sp_Modifica_Usuario(Nullable<int> idUsuario, Nullable<int> idTipoUsuario, string nombreUsuario, string apellido1, string apellido2, string direccion, string correo, string telefono, string clave, string usuarioIngreso, string estadoU, Nullable<System.DateTime> fechaCreado, Nullable<System.DateTime> ultimaVez, string cedula)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idTipoUsuarioParameter = idTipoUsuario.HasValue ?
                new ObjectParameter("idTipoUsuario", idTipoUsuario) :
                new ObjectParameter("idTipoUsuario", typeof(int));
    
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("nombreUsuario", nombreUsuario) :
                new ObjectParameter("nombreUsuario", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var usuarioIngresoParameter = usuarioIngreso != null ?
                new ObjectParameter("usuarioIngreso", usuarioIngreso) :
                new ObjectParameter("usuarioIngreso", typeof(string));
    
            var estadoUParameter = estadoU != null ?
                new ObjectParameter("estadoU", estadoU) :
                new ObjectParameter("estadoU", typeof(string));
    
            var fechaCreadoParameter = fechaCreado.HasValue ?
                new ObjectParameter("fechaCreado", fechaCreado) :
                new ObjectParameter("fechaCreado", typeof(System.DateTime));
    
            var ultimaVezParameter = ultimaVez.HasValue ?
                new ObjectParameter("ultimaVez", ultimaVez) :
                new ObjectParameter("ultimaVez", typeof(System.DateTime));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Usuario", idUsuarioParameter, idTipoUsuarioParameter, nombreUsuarioParameter, apellido1Parameter, apellido2Parameter, direccionParameter, correoParameter, telefonoParameter, claveParameter, usuarioIngresoParameter, estadoUParameter, fechaCreadoParameter, ultimaVezParameter, cedulaParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Usuario_Result> sp_Retorna_Usuario(string nombreUsuario, string apellido1)
        {
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("nombreUsuario", nombreUsuario) :
                new ObjectParameter("nombreUsuario", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Usuario_Result>("sp_Retorna_Usuario", nombreUsuarioParameter, apellido1Parameter);
        }
    
        public virtual ObjectResult<sp_Retorna_UsuarioID_Result> sp_Retorna_UsuarioID(Nullable<int> idUsuario, string nombreUsuario, string apellido1)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var nombreUsuarioParameter = nombreUsuario != null ?
                new ObjectParameter("nombreUsuario", nombreUsuario) :
                new ObjectParameter("nombreUsuario", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_UsuarioID_Result>("sp_Retorna_UsuarioID", idUsuarioParameter, nombreUsuarioParameter, apellido1Parameter);
        }
    
        public virtual int sp_Inserta_Products(Nullable<int> idCategoria, string nombrePRO, Nullable<decimal> precioPRO, string descripPRO, Nullable<bool> estadoPRO, Nullable<int> cantDisponible)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            var nombrePROParameter = nombrePRO != null ?
                new ObjectParameter("nombrePRO", nombrePRO) :
                new ObjectParameter("nombrePRO", typeof(string));
    
            var precioPROParameter = precioPRO.HasValue ?
                new ObjectParameter("precioPRO", precioPRO) :
                new ObjectParameter("precioPRO", typeof(decimal));
    
            var descripPROParameter = descripPRO != null ?
                new ObjectParameter("descripPRO", descripPRO) :
                new ObjectParameter("descripPRO", typeof(string));
    
            var estadoPROParameter = estadoPRO.HasValue ?
                new ObjectParameter("estadoPRO", estadoPRO) :
                new ObjectParameter("estadoPRO", typeof(bool));
    
            var cantDisponibleParameter = cantDisponible.HasValue ?
                new ObjectParameter("CantDisponible", cantDisponible) :
                new ObjectParameter("CantDisponible", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Products", idCategoriaParameter, nombrePROParameter, precioPROParameter, descripPROParameter, estadoPROParameter, cantDisponibleParameter);
        }
    
        public virtual int sp_Modifica_Products(Nullable<int> idPROD, Nullable<int> idCategoria, string nombrePRO, Nullable<decimal> precioPRO, string descripPRO, Nullable<bool> estadoPRO, Nullable<int> cantidadDisponible)
        {
            var idPRODParameter = idPROD.HasValue ?
                new ObjectParameter("idPROD", idPROD) :
                new ObjectParameter("idPROD", typeof(int));
    
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(int));
    
            var nombrePROParameter = nombrePRO != null ?
                new ObjectParameter("nombrePRO", nombrePRO) :
                new ObjectParameter("nombrePRO", typeof(string));
    
            var precioPROParameter = precioPRO.HasValue ?
                new ObjectParameter("precioPRO", precioPRO) :
                new ObjectParameter("precioPRO", typeof(decimal));
    
            var descripPROParameter = descripPRO != null ?
                new ObjectParameter("descripPRO", descripPRO) :
                new ObjectParameter("descripPRO", typeof(string));
    
            var estadoPROParameter = estadoPRO.HasValue ?
                new ObjectParameter("estadoPRO", estadoPRO) :
                new ObjectParameter("estadoPRO", typeof(bool));
    
            var cantidadDisponibleParameter = cantidadDisponible.HasValue ?
                new ObjectParameter("CantidadDisponible", cantidadDisponible) :
                new ObjectParameter("CantidadDisponible", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Products", idPRODParameter, idCategoriaParameter, nombrePROParameter, precioPROParameter, descripPROParameter, estadoPROParameter, cantidadDisponibleParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Productos_Result> sp_Retorna_Productos(string nombrePROD, string descripPROD)
        {
            var nombrePRODParameter = nombrePROD != null ?
                new ObjectParameter("nombrePROD", nombrePROD) :
                new ObjectParameter("nombrePROD", typeof(string));
    
            var descripPRODParameter = descripPROD != null ?
                new ObjectParameter("descripPROD", descripPROD) :
                new ObjectParameter("descripPROD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Productos_Result>("sp_Retorna_Productos", nombrePRODParameter, descripPRODParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Products_ID_Result> sp_Retorna_Products_ID(Nullable<int> idPROD)
        {
            var idPRODParameter = idPROD.HasValue ?
                new ObjectParameter("idPROD", idPROD) :
                new ObjectParameter("idPROD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Products_ID_Result>("sp_Retorna_Products_ID", idPRODParameter);
        }
    
        public virtual int sp_Inserta_Imagenes(Nullable<int> idproducto, string urlImagen, string descripImagen)
        {
            var idproductoParameter = idproducto.HasValue ?
                new ObjectParameter("idproducto", idproducto) :
                new ObjectParameter("idproducto", typeof(int));
    
            var urlImagenParameter = urlImagen != null ?
                new ObjectParameter("urlImagen", urlImagen) :
                new ObjectParameter("urlImagen", typeof(string));
    
            var descripImagenParameter = descripImagen != null ?
                new ObjectParameter("descripImagen", descripImagen) :
                new ObjectParameter("descripImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Inserta_Imagenes", idproductoParameter, urlImagenParameter, descripImagenParameter);
        }
    
        public virtual int sp_Modifica_Imagenes(Nullable<int> idImagen, Nullable<int> idproducto, string urlImagen, string descripImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("idImagen", idImagen) :
                new ObjectParameter("idImagen", typeof(int));
    
            var idproductoParameter = idproducto.HasValue ?
                new ObjectParameter("idproducto", idproducto) :
                new ObjectParameter("idproducto", typeof(int));
    
            var urlImagenParameter = urlImagen != null ?
                new ObjectParameter("urlImagen", urlImagen) :
                new ObjectParameter("urlImagen", typeof(string));
    
            var descripImagenParameter = descripImagen != null ?
                new ObjectParameter("descripImagen", descripImagen) :
                new ObjectParameter("descripImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Modifica_Imagenes", idImagenParameter, idproductoParameter, urlImagenParameter, descripImagenParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_Imagenes_Result> sp_Retorna_Imagenes(string urlImagen, string descripImagen)
        {
            var urlImagenParameter = urlImagen != null ?
                new ObjectParameter("urlImagen", urlImagen) :
                new ObjectParameter("urlImagen", typeof(string));
    
            var descripImagenParameter = descripImagen != null ?
                new ObjectParameter("descripImagen", descripImagen) :
                new ObjectParameter("descripImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_Imagenes_Result>("sp_Retorna_Imagenes", urlImagenParameter, descripImagenParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_ImagenesID_Result> sp_Retorna_ImagenesID(Nullable<int> idImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("idImagen", idImagen) :
                new ObjectParameter("idImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_ImagenesID_Result>("sp_Retorna_ImagenesID", idImagenParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_ImagenesIDPROD_Result> sp_Retorna_ImagenesIDPROD(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("idProducto", idProducto) :
                new ObjectParameter("idProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_ImagenesIDPROD_Result>("sp_Retorna_ImagenesIDPROD", idProductoParameter);
        }
    
        public virtual ObjectResult<sp_Retorna_ProductsImages_Result> sp_Retorna_ProductsImages(string nombrePROD)
        {
            var nombrePRODParameter = nombrePROD != null ?
                new ObjectParameter("nombrePROD", nombrePROD) :
                new ObjectParameter("nombrePROD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Retorna_ProductsImages_Result>("sp_Retorna_ProductsImages", nombrePRODParameter);
        }
    }
}
