//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int ID_Producto { get; set; }
        public int ID_Categoria { get; set; }
        public string Nombre_PRD { get; set; }
        public Nullable<decimal> Precio_PRD { get; set; }
        public string Descrip_PRD { get; set; }
        public bool Estado_PRD { get; set; }
    }
}
