//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosTbl
    {
        public ProductosTbl()
        {
            this.AjustesTbl = new HashSet<AjustesTbl>();
            this.DetalleCotizacionTbl = new HashSet<DetalleCotizacionTbl>();
            this.DetalleEntradaTbl = new HashSet<DetalleEntradaTbl>();
            this.DetalleSalidaTbl = new HashSet<DetalleSalidaTbl>();
        }
    
        public int ID_Producto { get; set; }
        public int ID_Categoria { get; set; }
        public string Nombre_PROD { get; set; }
        public decimal Precio_PROD { get; set; }
        public string Descripcion_PROD { get; set; }
        public bool Estado_PROD { get; set; }
        public Nullable<int> Cantidad_PROD { get; set; }
    
        public virtual ICollection<AjustesTbl> AjustesTbl { get; set; }
        public virtual CategoriasTbl CategoriasTbl { get; set; }
        public virtual ICollection<DetalleCotizacionTbl> DetalleCotizacionTbl { get; set; }
        public virtual ICollection<DetalleEntradaTbl> DetalleEntradaTbl { get; set; }
        public virtual ICollection<DetalleSalidaTbl> DetalleSalidaTbl { get; set; }
    }
}
