//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedoresTbl
    {
        public ProveedoresTbl()
        {
            this.EntradasTbl = new HashSet<EntradasTbl>();
        }
    
        public int ID_Proveedor { get; set; }
        public string Nombre_PROV { get; set; }
        public string Direccion_PROV { get; set; }
        public string Correo_PROV { get; set; }
        public string Telefono_PROV { get; set; }
        public bool Estado_PROV { get; set; }
    
        public virtual ICollection<EntradasTbl> EntradasTbl { get; set; }
    }
}
