//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidasTbl
    {
        public SalidasTbl()
        {
            this.DetalleSalidaTbl = new HashSet<DetalleSalidaTbl>();
        }
    
        public int ID_Salida { get; set; }
        public int ID_Usuario { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public System.TimeSpan Hora_Orden { get; set; }
    
        public virtual ICollection<DetalleSalidaTbl> DetalleSalidaTbl { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
