//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaIIICO.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_ServicioTbl
    {
        public Tipo_ServicioTbl()
        {
            this.ServiciosTbl = new HashSet<ServiciosTbl>();
        }
    
        public int ID_TipoServicio { get; set; }
        public string Nombre_TipoServicio { get; set; }
        public string Descripcion_TipoServicio { get; set; }
    
        public virtual ICollection<ServiciosTbl> ServiciosTbl { get; set; }
    }
}
